import { Word, Category } from '@/types/vocabulary';

export const CATEGORIES: Category[] = [
  {
    id: 'daily-english',
    name: 'Daily English',
    description: 'Everyday vocabulary for conversation, routines and social life',
    icon: 'Coffee',
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    totalWords: 25,
    levelRange: 'A1–B1',
  },
  {
    id: 'it-programming',
    name: 'IT & Programming',
    description: 'Tech terminology, software engineering and digital concepts',
    icon: 'Code2',
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-600',
    totalWords: 24,
    levelRange: 'B1–C1',
  },
  {
    id: 'ielts',
    name: 'IELTS / TOEFL',
    description: 'Academic and advanced lexical items for band 7.5+ and 100+ scores',
    icon: 'GraduationCap',
    color: 'indigo',
    gradient: 'from-indigo-500 to-purple-600',
    totalWords: 25,
    levelRange: 'B2–C1',
  },
  {
    id: 'university',
    name: 'University & Academia',
    description: 'Formal expressions for academic research, essays and lectures',
    icon: 'BookOpen',
    color: 'amber',
    gradient: 'from-amber-500 to-orange-600',
    totalWords: 22,
    levelRange: 'B2–C1',
  },
  {
    id: 'work',
    name: 'Work & Business',
    description: 'Professional workplace communication, meetings and negotiation',
    icon: 'Briefcase',
    color: 'blue',
    gradient: 'from-blue-500 to-indigo-600',
    totalWords: 22,
    levelRange: 'B1–B2',
  },
  {
    id: 'travel',
    name: 'Travel & Mobility',
    description: 'Essential phrases for airports, hotels, directions and exploring',
    icon: 'Plane',
    color: 'rose',
    gradient: 'from-rose-500 to-pink-600',
    totalWords: 20,
    levelRange: 'A1–B1',
  },
  {
    id: 'phrasal-verbs',
    name: 'Phrasal Verbs',
    description: 'Crucial combinations native speakers use in casual dialogue',
    icon: 'Sparkles',
    color: 'purple',
    gradient: 'from-purple-500 to-violet-600',
    totalWords: 15,
    levelRange: 'A2–B2',
  },
];

export const SEED_WORDS: Word[] = [
  // --- DAILY ENGLISH (A1 - B1) ---
  {
    id: 'de-1',
    word: 'achieve',
    translation_ru: 'достигать',
    translation_kz: 'жету',
    definition: 'to successfully reach a goal or result by effort or skill',
    example: 'I want to achieve a high TOEFL score this autumn.',
    pronunciation: '/əˈtʃiːv/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['accomplish', 'reach', 'attain', 'fulfill'],
    antonyms: ['fail', 'give up'],
  },
  {
    id: 'de-2',
    word: 'avoid',
    translation_ru: 'избегать',
    translation_kz: 'аулақ болу',
    definition: 'to stay away from someone or prevent something from happening',
    example: 'I try to avoid wasting time on social media during study sessions.',
    pronunciation: '/əˈvɔɪd/',
    part_of_speech: 'Verb',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['dodge', 'evade', 'bypass', 'shun'],
    antonyms: ['confront', 'face'],
  },
  {
    id: 'de-3',
    word: 'improve',
    translation_ru: 'улучшать',
    translation_kz: 'жақсарту',
    definition: 'to make or become better in quality or performance',
    example: 'Practicing ten minutes every day will improve your fluency.',
    pronunciation: '/ɪmˈpruːv/',
    part_of_speech: 'Verb',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['enhance', 'upgrade', 'boost', 'refine'],
    antonyms: ['worsen', 'deteriorate'],
  },
  {
    id: 'de-4',
    word: 'require',
    translation_ru: 'требовать',
    translation_kz: 'талап ету',
    definition: 'to need something for a particular purpose or under certain conditions',
    example: 'Active recall and spaced repetition require regular mental effort.',
    pronunciation: '/rɪˈkwaɪər/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['demand', 'need', 'necessitate'],
    antonyms: ['optional', 'exclude'],
  },
  {
    id: 'de-5',
    word: 'reduce',
    translation_ru: 'уменьшать',
    translation_kz: 'азайту',
    definition: 'to make something smaller in size, amount, degree, or price',
    example: 'Taking short breaks can help reduce stress and eye fatigue.',
    pronunciation: '/rɪˈdjuːs/',
    part_of_speech: 'Verb',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['decrease', 'diminish', 'lower', 'curb'],
    antonyms: ['increase', 'expand'],
  },
  {
    id: 'de-6',
    word: 'increase',
    translation_ru: 'увеличивать',
    translation_kz: 'көбейту',
    definition: 'to become or make greater in size, amount, intensity, or degree',
    example: 'Reading authentic books will steadily increase your vocabulary.',
    pronunciation: '/ɪnˈkriːs/',
    part_of_speech: 'Verb',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['grow', 'expand', 'raise', 'multiply'],
    antonyms: ['reduce', 'decrease'],
  },
  {
    id: 'de-7',
    word: 'encourage',
    translation_ru: 'поощрять',
    translation_kz: 'жігерлендіру',
    definition: 'to give support, confidence, or hope to someone',
    example: 'Our teacher always encourages us to speak English without fear.',
    pronunciation: '/ɪnˈkʌr.ɪdʒ/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['motivate', 'cheer', 'support', 'inspire'],
    antonyms: ['discourage', 'dissuade'],
  },
  {
    id: 'de-8',
    word: 'convenient',
    translation_ru: 'удобный',
    translation_kz: 'ыңғайлы',
    definition: 'fitting in well with a person needs, activities, and plans',
    example: 'Learning on a mobile device is very convenient on the subway.',
    pronunciation: '/kənˈviː.ni.ənt/',
    part_of_speech: 'Adjective',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['handy', 'suitable', 'accessible', 'practical'],
    antonyms: ['inconvenient', 'troublesome'],
  },
  {
    id: 'de-9',
    word: 'habit',
    translation_ru: 'привычка',
    translation_kz: 'әдет',
    definition: 'a settled or regular tendency or practice, especially one hard to give up',
    example: 'Studying vocabulary every morning has become my favorite habit.',
    pronunciation: '/ˈhæb.ɪt/',
    part_of_speech: 'Noun',
    level: 'A1',
    category_id: 'daily-english',
    synonyms: ['routine', 'custom', 'pattern'],
    antonyms: [],
  },
  {
    id: 'de-10',
    word: 'opportunity',
    translation_ru: 'возможность',
    translation_kz: 'мүмкіндік',
    definition: 'a set of circumstances that makes it possible to do something',
    example: 'Speaking with native speakers is a wonderful opportunity.',
    pronunciation: '/ˌɒp.əˈtjuː.nə.ti/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['chance', 'opening', 'possibility'],
    antonyms: ['obstacle'],
  },
  {
    id: 'de-11',
    word: 'hesitate',
    translation_ru: 'колебаться',
    translation_kz: 'кідіру',
    definition: 'to pause before saying or doing something because of uncertainty',
    example: 'Do not hesitate to ask questions whenever you do not understand.',
    pronunciation: '/ˈhez.ɪ.teɪt/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['waver', 'delay', 'pause', 'doubt'],
    antonyms: ['resolve', 'proceed'],
  },
  {
    id: 'de-12',
    word: 'valuable',
    translation_ru: 'ценный',
    translation_kz: 'құнды',
    definition: 'worth a great deal of money or having immense practical importance',
    example: 'Constructive feedback from mentors is extremely valuable.',
    pronunciation: '/ˈvæl.jʊ.bəl/',
    part_of_speech: 'Adjective',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['precious', 'worthwhile', 'beneficial', 'treasured'],
    antonyms: ['worthless', 'useless'],
  },
  {
    id: 'de-13',
    word: 'confident',
    translation_ru: 'уверенный',
    translation_kz: 'сенімді',
    definition: 'feeling or showing certainty about something or your own ability',
    example: 'After three weeks of speaking practice, she felt much more confident.',
    pronunciation: '/ˈkɒn.fɪ.dənt/',
    part_of_speech: 'Adjective',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['assured', 'self-reliant', 'positive'],
    antonyms: ['insecure', 'timid'],
  },
  {
    id: 'de-14',
    word: 'express',
    translation_ru: 'выражать',
    translation_kz: 'білдіру',
    definition: 'to convey a thought, feeling, or opinion in words or by gestures',
    example: 'It is important to clearly express your perspective in discussions.',
    pronunciation: '/ɪkˈspres/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['articulate', 'voice', 'convey', 'state'],
    antonyms: ['suppress', 'hide'],
  },
  {
    id: 'de-15',
    word: 'fluent',
    translation_ru: 'беглый',
    translation_kz: 'еркін сөйлейтін',
    definition: 'able to express oneself easily, smoothly, and articulately',
    example: 'He aims to become completely fluent in English within six months.',
    pronunciation: '/ˈfluː.ənt/',
    part_of_speech: 'Adjective',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['articulate', 'effortless', 'smooth'],
    antonyms: ['halting', 'hesitant'],
  },
  {
    id: 'de-16',
    word: 'curious',
    translation_ru: 'любопытный',
    translation_kz: 'қызыққұмар',
    definition: 'eager to know or learn something new and interesting',
    example: 'Children are naturally curious about the world around them.',
    pronunciation: '/ˈkjʊə.ri.əs/',
    part_of_speech: 'Adjective',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['inquisitive', 'interested', 'intrigued'],
    antonyms: ['indifferent', 'apathetic'],
  },
  {
    id: 'de-17',
    word: 'delicious',
    translation_ru: 'вкусный',
    translation_kz: 'дәмді',
    definition: 'highly pleasant to the taste or smell',
    example: 'We had a delicious dinner at an authentic Italian restaurant.',
    pronunciation: '/dɪˈlɪʃ.əs/',
    part_of_speech: 'Adjective',
    level: 'A1',
    category_id: 'daily-english',
    synonyms: ['tasty', 'flavorful', 'yummy'],
    antonyms: ['disgusting', 'bland'],
  },
  {
    id: 'de-18',
    word: 'patience',
    translation_ru: 'терпение',
    translation_kz: 'шыдамдылық',
    definition: 'the capacity to accept or tolerate delay, trouble, or suffering without anger',
    example: 'Mastering a foreign language requires endless patience and dedication.',
    pronunciation: '/ˈpeɪ.ʃəns/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'daily-english',
    synonyms: ['perseverance', 'endurance', 'tolerance'],
    antonyms: ['impatience', 'irritation'],
  },
  {
    id: 'de-19',
    word: 'simple',
    translation_ru: 'простой',
    translation_kz: 'қарапайым',
    definition: 'easily understood or done; presenting no difficulty',
    example: 'The rule is simple: review each card before the timer runs out.',
    pronunciation: '/ˈsɪm.pəl/',
    part_of_speech: 'Adjective',
    level: 'A1',
    category_id: 'daily-english',
    synonyms: ['easy', 'straightforward', 'uncomplicated'],
    antonyms: ['complex', 'complicated'],
  },
  {
    id: 'de-20',
    word: 'routine',
    translation_ru: 'распорядок',
    translation_kz: 'күн тәртібі',
    definition: 'a sequence of actions regularly followed; a fixed program',
    example: 'A healthy morning routine includes stretching and reviewing flashcards.',
    pronunciation: '/ruːˈtiːn/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'daily-english',
    synonyms: ['schedule', 'regimen', 'habit'],
    antonyms: ['irregularity'],
  },

  // --- IT & PROGRAMMING (B1 - C1) ---
  {
    id: 'it-1',
    word: 'implement',
    translation_ru: 'внедрять',
    translation_kz: 'енгізу',
    definition: 'to put a decision, plan, system, or agreement into effect or code',
    example: 'We need to implement spaced repetition algorithms in our web app.',
    pronunciation: '/ˈɪm.plɪ.ment/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['execute', 'deploy', 'apply', 'enact'],
    antonyms: ['cancel', 'neglect'],
  },
  {
    id: 'it-2',
    word: 'scalable',
    translation_ru: 'масштабируемый',
    translation_kz: 'масштабталатын',
    definition: 'able to be changed in size or scale to handle growing workloads',
    example: 'Cloud architecture ensures that the database remains highly scalable.',
    pronunciation: '/ˈskeɪ.lə.bəl/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['expandable', 'adaptable', 'flexible'],
    antonyms: ['rigid', 'limited'],
  },
  {
    id: 'it-3',
    word: 'optimize',
    translation_ru: 'оптимизировать',
    translation_kz: 'оңтайландыру',
    definition: 'to make the best or most effective use of a situation or software code',
    example: 'We must optimize SQL queries to reduce server response latency.',
    pronunciation: '/ˈɒp.tɪ.maɪz/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['streamline', 'enhance', 'fine-tune', 'perfect'],
    antonyms: ['degrade', 'worsen'],
  },
  {
    id: 'it-4',
    word: 'redundant',
    translation_ru: 'избыточный',
    translation_kz: 'артық',
    definition: 'not or no longer needed or useful; superfluous in data or logic',
    example: 'Clean code eliminates redundant state updates and duplicated logic.',
    pronunciation: '/rɪˈdʌn.dənt/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'it-programming',
    synonyms: ['superfluous', 'surplus', 'excess', 'unnecessary'],
    antonyms: ['essential', 'indispensable'],
  },
  {
    id: 'it-5',
    word: 'deprecated',
    translation_ru: 'устаревший',
    translation_kz: 'ескірген',
    definition: 'declared obsolete and not recommended for use in software versions',
    example: 'This lifecycle hook is deprecated in React 19 in favor of hooks.',
    pronunciation: '/ˈdep.rə.keɪ.tɪd/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['obsolete', 'outdated', 'superseded'],
    antonyms: ['current', 'supported'],
  },
  {
    id: 'it-6',
    word: 'authenticate',
    translation_ru: 'аутентифицировать',
    translation_kz: 'түпнұсқасын растау',
    definition: 'to prove or verify that something or a user is who they claim to be',
    example: 'Users can authenticate securely using Supabase OAuth or JWT tokens.',
    pronunciation: '/ɔːˈθen.tɪ.keɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['verify', 'validate', 'certify', 'confirm'],
    antonyms: ['invalidate', 'falsify'],
  },
  {
    id: 'it-7',
    word: 'robust',
    translation_ru: 'надежный',
    translation_kz: 'мықты',
    definition: 'able to withstand or overcome adverse conditions without crashing',
    example: 'A robust error handling strategy keeps the application responsive.',
    pronunciation: '/rəʊˈbʌst/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['sturdy', 'resilient', 'sound', 'durable'],
    antonyms: ['fragile', 'flimsy'],
  },
  {
    id: 'it-8',
    word: 'concurrency',
    translation_ru: 'параллелизм',
    translation_kz: 'қатар жүру',
    definition: 'the ability of different parts of a program to be executed out-of-order or in partial order',
    example: 'React fiber engine handles UI concurrency with smooth frame rates.',
    pronunciation: '/kənˈkʌr.ən.si/',
    part_of_speech: 'Noun',
    level: 'C1',
    category_id: 'it-programming',
    synonyms: ['parallelism', 'simultaneity'],
    antonyms: ['sequentiality'],
  },
  {
    id: 'it-9',
    word: 'latency',
    translation_ru: 'задержка',
    translation_kz: 'кідіріс',
    definition: 'the delay before a transfer of data begins following an instruction for its transfer',
    example: 'Edge CDN caching drastically reduces network latency worldwide.',
    pronunciation: '/ˈleɪ.tən.si/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['delay', 'lag', 'deferral'],
    antonyms: ['promptness', 'speed'],
  },
  {
    id: 'it-10',
    word: 'pipeline',
    translation_ru: 'конвейер',
    translation_kz: 'конвейер',
    definition: 'a set of automated data processing elements connected in series',
    example: 'Our CI/CD pipeline runs unit tests before deploying to Vercel.',
    pronunciation: '/ˈpaɪp.laɪn/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['workflow', 'channel', 'process'],
    antonyms: [],
  },
  {
    id: 'it-11',
    word: 'immutable',
    translation_ru: 'неизменяемый',
    translation_kz: 'өзгермейтін',
    definition: 'unchanging over time or unable to be altered after creation',
    example: 'In functional programming, state updates produce immutable copies.',
    pronunciation: '/ɪˈmjuː.tə.bəl/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'it-programming',
    synonyms: ['unalterable', 'permanent', 'fixed'],
    antonyms: ['mutable', 'changeable'],
  },
  {
    id: 'it-12',
    word: 'vulnerability',
    translation_ru: 'уязвимость',
    translation_kz: 'осал тұс',
    definition: 'a weakness in a computer system or network that can be exploited by threats',
    example: 'Regular security audits detect potential vulnerability issues early.',
    pronunciation: '/ˌvʌl.nər.əˈbɪl.ə.ti/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['weakness', 'flaw', 'hole', 'exposure'],
    antonyms: ['security', 'safeguard'],
  },
  {
    id: 'it-13',
    word: 'refactor',
    translation_ru: 'рефакторить',
    translation_kz: 'қайта құру',
    definition: 'to restructure existing computer code without changing its external behavior',
    example: 'Let us refactor this huge component into smaller reusable hooks.',
    pronunciation: '/riːˈfæk.tər/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['clean up', 'reorganize', 'streamline'],
    antonyms: [],
  },
  {
    id: 'it-14',
    word: 'framework',
    translation_ru: 'фреймворк',
    translation_kz: 'негіздеме',
    definition: 'a basic structure underlying a system, concept, or software application',
    example: 'Next.js is a full-stack React framework optimized for web performance.',
    pronunciation: '/ˈfreɪm.wɜːk/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'it-programming',
    synonyms: ['structure', 'scaffolding', 'platform'],
    antonyms: [],
  },
  {
    id: 'it-15',
    word: 'interface',
    translation_ru: 'интерфейс',
    translation_kz: 'интерфейс',
    definition: 'a point where two systems, subjects, or software components meet and interact',
    example: 'A clean user interface improves retention and learner satisfaction.',
    pronunciation: '/ˈɪn.tə.feɪs/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'it-programming',
    synonyms: ['boundary', 'connection', 'dashboard'],
    antonyms: [],
  },
  {
    id: 'it-16',
    word: 'repository',
    translation_ru: 'репозиторий',
    translation_kz: 'қойма',
    definition: 'a central location in which data or version-controlled code is stored and managed',
    example: 'Push your commits to the Git repository before creating a pull request.',
    pronunciation: '/rɪˈpɒz.ɪ.tər.i/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['storehouse', 'depository', 'registry'],
    antonyms: [],
  },
  {
    id: 'it-17',
    word: 'syntax',
    translation_ru: 'синтаксис',
    translation_kz: 'синтаксис',
    definition: 'the arrangement of words or symbols to create well-formed sentences or code',
    example: 'TypeScript catches syntax mistakes and type errors during compilation.',
    pronunciation: '/ˈsɪn.tæks/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'it-programming',
    synonyms: ['structure', 'grammar', 'rules'],
    antonyms: [],
  },
  {
    id: 'it-18',
    word: 'algorithm',
    translation_ru: 'алгоритм',
    translation_kz: 'алгоритм',
    definition: 'a process or set of rules to be followed in calculations or problem-solving',
    example: 'The spaced repetition algorithm calculates the optimal review interval.',
    pronunciation: '/ˈæl.ɡə.rɪ.ðəm/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'it-programming',
    synonyms: ['procedure', 'formula', 'logic'],
    antonyms: [],
  },
  {
    id: 'it-19',
    word: 'asynchronous',
    translation_ru: 'асинхронный',
    translation_kz: 'асинхронды',
    definition: 'not occurring at the same time; happening in the background without blocking',
    example: 'Async functions allow network requests without freezing the user interface.',
    pronunciation: '/eɪˈsɪŋ.krə.nəs/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['non-blocking', 'independent'],
    antonyms: ['synchronous'],
  },
  {
    id: 'it-20',
    word: 'deployment',
    translation_ru: 'развертывание',
    translation_kz: 'орналастыру',
    definition: 'the action of bringing software into effective operation on a server',
    example: 'The production deployment went live without any server downtime.',
    pronunciation: '/dɪˈplɔɪ.mənt/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'it-programming',
    synonyms: ['rollout', 'release', 'distribution'],
    antonyms: ['rollback'],
  },

  // --- IELTS / TOEFL (B2 - C1) ---
  {
    id: 'ielts-1',
    word: 'significant',
    translation_ru: 'значительный',
    translation_kz: 'маңызды',
    definition: 'sufficiently great or important to be worthy of attention; noteworthy',
    example: 'There has been a significant improvement in global literacy rates.',
    pronunciation: '/sɪɡˈnɪf.ɪ.kənt/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['notable', 'substantial', 'considerable', 'momentous'],
    antonyms: ['insignificant', 'trivial', 'negligible'],
  },
  {
    id: 'ielts-2',
    word: 'inevitable',
    translation_ru: 'неизбежный',
    translation_kz: 'болмай қоймайтын',
    definition: 'certain to happen; unavoidable',
    example: 'Technological disruption is an inevitable part of economic development.',
    pronunciation: '/ɪnˈev.ɪ.tə.bəl/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['unavoidable', 'inescapable', 'fated', 'destined'],
    antonyms: ['preventable', 'avoidable'],
  },
  {
    id: 'ielts-3',
    word: 'subtle',
    translation_ru: 'тонкий',
    translation_kz: 'нәзік',
    definition: 'so delicate or precise as to be difficult to analyze or notice immediately',
    example: 'There is a subtle distinction between passive recognition and active recall.',
    pronunciation: '/ˈsʌt.əl/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['delicate', 'fine', 'understated', 'nuanced'],
    antonyms: ['obvious', 'blatant', 'crude'],
  },
  {
    id: 'ielts-4',
    word: 'comprehensive',
    translation_ru: 'всесторонний',
    translation_kz: 'жан-жақты',
    definition: 'complete; including all or nearly all elements or aspects of something',
    example: 'The university offers a comprehensive overview of modern linguistic theory.',
    pronunciation: '/ˌkɒm.prɪˈhen.sɪv/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['thorough', 'exhaustive', 'all-inclusive', 'extensive'],
    antonyms: ['partial', 'selective', 'limited'],
  },
  {
    id: 'ielts-5',
    word: 'consequence',
    translation_ru: 'последствие',
    translation_kz: 'салдары',
    definition: 'a result or effect of an action or condition',
    example: 'Climate shifts have profound consequences for agricultural sustainability.',
    pronunciation: '/ˈkɒn.sɪ.kwəns/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['outcome', 'repercussion', 'aftermath', 'ramification'],
    antonyms: ['cause', 'origin'],
  },
  {
    id: 'ielts-6',
    word: 'sustainable',
    translation_ru: 'устойчивый',
    translation_kz: 'тұрақты',
    definition: 'able to be maintained at a certain rate or level without exhausting resources',
    example: 'Daily 15-minute practice is far more sustainable than weekend cramming.',
    pronunciation: '/səˈsteɪ.nə.bəl/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['viable', 'maintainable', 'enduring'],
    antonyms: ['unsustainable', 'short-lived'],
  },
  {
    id: 'ielts-7',
    word: 'predominantly',
    translation_ru: 'преимущественно',
    translation_kz: 'басым түрде',
    definition: 'mainly; for the most part; to a greater extent than other factors',
    example: 'International academic papers are predominantly published in English.',
    pronunciation: '/prɪˈdɒm.ɪ.nənt.li/',
    part_of_speech: 'Adverb',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['chiefly', 'primarily', 'principally', 'largely'],
    antonyms: ['secondarily', 'partially'],
  },
  {
    id: 'ielts-8',
    word: 'profound',
    translation_ru: 'глубокий',
    translation_kz: 'терең',
    definition: 'very great, intense, or having deep insight and meaning',
    example: 'Reading literature has a profound impact on cognitive development.',
    pronunciation: '/prəˈfaʊnd/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['deep', 'intense', 'far-reaching', 'weighty'],
    antonyms: ['superficial', 'shallow'],
  },
  {
    id: 'ielts-9',
    word: 'ambiguous',
    translation_ru: 'двусмысленный',
    translation_kz: 'екіұшты',
    definition: 'open to more than one interpretation; not having one obvious meaning',
    example: 'Phrasing in exam prompts should be explicit rather than ambiguous.',
    pronunciation: '/æmˈbɪɡ.ju.əs/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['equivocal', 'unclear', 'vague', 'enigmatic'],
    antonyms: ['explicit', 'clear', 'definite'],
  },
  {
    id: 'ielts-10',
    word: 'facilitate',
    translation_ru: 'способствовать',
    translation_kz: 'жеңілдету',
    definition: 'to make an action or process easy or easier to accomplish',
    example: 'Smart flashcards facilitate effortless memory consolidation.',
    pronunciation: '/fəˈsɪl.ɪ.teɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['ease', 'promote', 'aid', 'accelerate'],
    antonyms: ['hinder', 'impede'],
  },
  {
    id: 'ielts-11',
    word: 'deteriorate',
    translation_ru: 'ухудшаться',
    translation_kz: 'нашарлау',
    definition: 'to become progressively worse in condition or value',
    example: 'Language skills deteriorate rapidly if not practiced frequently.',
    pronunciation: '/dɪˈtɪə.ri.ə.reɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['decline', 'degrade', 'degenerate'],
    antonyms: ['improve', 'ameliorate'],
  },
  {
    id: 'ielts-12',
    word: 'feasible',
    translation_ru: 'осуществимый',
    translation_kz: 'жүзеге асырылатын',
    definition: 'possible to do easily or conveniently; practicable',
    example: 'Memorizing 15 target words daily is a highly feasible goal.',
    pronunciation: '/ˈfiː.zə.bəl/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['viable', 'attainable', 'achievable', 'practical'],
    antonyms: ['impossible', 'impractical'],
  },
  {
    id: 'ielts-13',
    word: 'scrutinize',
    translation_ru: 'тщательно исследовать',
    translation_kz: 'мұқият зерттеу',
    definition: 'to examine or inspect closely and thoroughly',
    example: 'IELTS examiners scrutinize lexical resource and grammatical accuracy.',
    pronunciation: '/ˈskruː.tɪ.naɪz/',
    part_of_speech: 'Verb',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['inspect', 'audit', 'examine', 'dissect'],
    antonyms: ['glance', 'ignore'],
  },
  {
    id: 'ielts-14',
    word: 'coherent',
    translation_ru: 'связный',
    translation_kz: 'байланысты',
    definition: 'logical and consistent; forming a unified whole in speech or writing',
    example: 'A coherent essay structure earns top marks in IELTS Academic Task 2.',
    pronunciation: '/kəʊˈhɪə.rənt/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['logical', 'lucid', 'cohesive', 'articulate'],
    antonyms: ['incoherent', 'disjointed'],
  },
  {
    id: 'ielts-15',
    word: 'prevalent',
    translation_ru: 'распространенный',
    translation_kz: 'кең таралған',
    definition: 'widespread in a particular area or at a particular time',
    example: 'Passive learning habits are unfortunately prevalent among novice students.',
    pronunciation: '/ˈprev.əl.ənt/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['widespread', 'common', 'pervasive', 'ubiquitous'],
    antonyms: ['rare', 'uncommon'],
  },
  {
    id: 'ielts-16',
    word: 'discrepancy',
    translation_ru: 'несоответствие',
    translation_kz: 'сәйкессіздік',
    definition: 'a lack of compatibility or similarity between two or more facts',
    example: 'There was a noticeable discrepancy between the two statistical reports.',
    pronunciation: '/dɪˈskrep.ən.si/',
    part_of_speech: 'Noun',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['inconsistency', 'mismatch', 'divergence'],
    antonyms: ['consistency', 'similarity'],
  },
  {
    id: 'ielts-17',
    word: 'ubiquitous',
    translation_ru: 'вездесущий',
    translation_kz: 'барлық жерде бар',
    definition: 'present, appearing, or found everywhere at the same time',
    example: 'Smartphones and digital interfaces have become ubiquitous in daily life.',
    pronunciation: '/juːˈbɪk.wɪ.təs/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'ielts',
    synonyms: ['omnipresent', 'universal', 'all-pervasive'],
    antonyms: ['rare', 'scarce'],
  },
  {
    id: 'ielts-18',
    word: 'diminish',
    translation_ru: 'уменьшаться',
    translation_kz: 'кішірею',
    definition: 'to make or become less; cause to seem less impressive or valuable',
    example: 'Lack of sleep can diminish mental clarity and concentration.',
    pronunciation: '/dɪˈmɪn.ɪʃ/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['lessen', 'decrease', 'wane', 'fade'],
    antonyms: ['enhance', 'magnify'],
  },
  {
    id: 'ielts-19',
    word: 'exemplify',
    translation_ru: 'служить примером',
    translation_kz: 'үлгі болу',
    definition: 'to be a typical example of; to illustrate by giving an example',
    example: 'Her rapid progress exemplifies the effectiveness of daily habit streaks.',
    pronunciation: '/ɪɡˈzem.plɪ.faɪ/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['illustrate', 'embody', 'demonstrate', 'epitomize'],
    antonyms: [],
  },
  {
    id: 'ielts-20',
    word: 'advocate',
    translation_ru: 'выступать за',
    translation_kz: 'жақтау',
    definition: 'to publicly recommend or support a particular cause or policy',
    example: 'Educators strongly advocate interactive learning over rote memorization.',
    pronunciation: '/ˈæd.və.keɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'ielts',
    synonyms: ['champion', 'endorse', 'promote', 'back'],
    antonyms: ['oppose', 'condemn'],
  },

  // --- UNIVERSITY & ACADEMIA (B2 - C1) ---
  {
    id: 'uni-1',
    word: 'hypothesis',
    translation_ru: 'гипотеза',
    translation_kz: 'болжам',
    definition: 'a proposed explanation made on the basis of limited evidence as a starting point',
    example: 'The laboratory experiment supported the researcher initial hypothesis.',
    pronunciation: '/haɪˈpɒθ.ə.sɪs/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['theory', 'postulate', 'proposition', 'conjecture'],
    antonyms: ['fact', 'certainty'],
  },
  {
    id: 'uni-2',
    word: 'methodology',
    translation_ru: 'методология',
    translation_kz: 'әдіснама',
    definition: 'a system of methods and principles used in a particular area of study',
    example: 'The dissertation chapter describes the qualitative research methodology.',
    pronunciation: '/ˌmeθ.əˈdɒl.ə.dʒi/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['approach', 'procedure', 'framework'],
    antonyms: [],
  },
  {
    id: 'uni-3',
    word: 'empirical',
    translation_ru: 'эмпирический',
    translation_kz: 'тәжірибелік',
    definition: 'based on, concerned with, or verifiable by observation rather than pure theory',
    example: 'Empirical studies prove that retrieval practice strengthens synaptic memory.',
    pronunciation: '/ɪmˈpɪr.ɪ.kəl/',
    part_of_speech: 'Adjective',
    level: 'C1',
    category_id: 'university',
    synonyms: ['observational', 'experimental', 'practical', 'factual'],
    antonyms: ['theoretical', 'hypothetical'],
  },
  {
    id: 'uni-4',
    word: 'synthesize',
    translation_ru: 'синтезировать',
    translation_kz: 'жинақтау',
    definition: 'to combine different ideas, styles, or systems into a coherent single entity',
    example: 'Students must synthesize multiple historical sources in their term paper.',
    pronunciation: '/ˈsɪn.θə.saɪz/',
    part_of_speech: 'Verb',
    level: 'C1',
    category_id: 'university',
    synonyms: ['integrate', 'amalgamate', 'blend', 'fuse'],
    antonyms: ['dissect', 'separate'],
  },
  {
    id: 'uni-5',
    word: 'paradigm',
    translation_ru: 'парадигма',
    translation_kz: 'үлгі',
    definition: 'a typical example or pattern of something; a distinct model of thought',
    example: 'The discovery marked a major paradigm shift in modern neuroscience.',
    pronunciation: '/ˈpær.ə.daɪm/',
    part_of_speech: 'Noun',
    level: 'C1',
    category_id: 'university',
    synonyms: ['model', 'archetype', 'benchmark', 'standard'],
    antonyms: [],
  },
  {
    id: 'uni-6',
    word: 'cite',
    translation_ru: 'цитировать',
    translation_kz: 'дәйексөз келтіру',
    definition: 'to quote a passage, book, or author as evidence or justification for an argument',
    example: 'Be sure to properly cite all academic sources following APA guidelines.',
    pronunciation: '/saɪt/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'university',
    synonyms: ['quote', 'reference', 'mention', 'allude to'],
    antonyms: [],
  },
  {
    id: 'uni-7',
    word: 'critique',
    translation_ru: 'критический разбор',
    translation_kz: 'сын',
    definition: 'a detailed analysis and assessment of something, especially a literary theory',
    example: 'The seminar began with a thoughtful critique of economic models.',
    pronunciation: '/krɪˈtiːk/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['analysis', 'evaluation', 'review', 'appraisal'],
    antonyms: [],
  },
  {
    id: 'uni-8',
    word: 'correlation',
    translation_ru: 'корреляция',
    translation_kz: 'байланыс',
    definition: 'a mutual relationship or connection between two or more things',
    example: 'Research shows a strong correlation between active recall and high test scores.',
    pronunciation: '/ˌkɒr.əˈleɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['link', 'association', 'interrelation'],
    antonyms: ['independence', 'disconnection'],
  },
  {
    id: 'uni-9',
    word: 'curriculum',
    translation_ru: 'учебная программа',
    translation_kz: 'оқу бағдарламасы',
    definition: 'the subjects comprising a course of study in a school or college',
    example: 'The modern university curriculum includes interdisciplinary data ethics.',
    pronunciation: '/kəˈrɪk.jə.ləm/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'university',
    synonyms: ['syllabus', 'course', 'program'],
    antonyms: [],
  },
  {
    id: 'uni-10',
    word: 'dissertation',
    translation_ru: 'диссертация',
    translation_kz: 'диссертация',
    definition: 'a long essay on a particular subject written for a university degree',
    example: 'She spent two years compiling primary source archives for her dissertation.',
    pronunciation: '/ˌdɪs.əˈteɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['thesis', 'treatise', 'paper'],
    antonyms: [],
  },
  {
    id: 'uni-11',
    word: 'qualitative',
    translation_ru: 'качественный',
    translation_kz: 'сапалық',
    definition: 'relating to, measuring, or measured by the quality rather than quantity',
    example: 'The study gathered qualitative interview feedback from fifty participants.',
    pronunciation: '/ˈkwɒl.ɪ.tə.tɪv/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'university',
    synonyms: ['descriptive', 'non-numerical'],
    antonyms: ['quantitative'],
  },
  {
    id: 'uni-12',
    word: 'quantitative',
    translation_ru: 'количественный',
    translation_kz: 'сандық',
    definition: 'relating to, measuring, or measured by the quantity rather than quality',
    example: 'Quantitative analysis revealed statistically significant vocabulary growth.',
    pronunciation: '/ˈkwɒn.tɪ.tə.tɪv/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'university',
    synonyms: ['numerical', 'statistical', 'measurable'],
    antonyms: ['qualitative'],
  },
  {
    id: 'uni-13',
    word: 'plagiarism',
    translation_ru: 'плагиат',
    translation_kz: 'плагиат',
    definition: 'the practice of taking someone else work and passing it off as one own',
    example: 'Academic honesty tools strictly screen every assignment for plagiarism.',
    pronunciation: '/ˈpleɪ.dʒər.ɪ.zəm/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['copying', 'infringement', 'appropriation'],
    antonyms: ['originality'],
  },
  {
    id: 'uni-14',
    word: 'coherent',
    translation_ru: 'последовательный',
    translation_kz: 'жүйелі',
    definition: 'holding together in a clear, sensible, and unified logical arrangement',
    example: 'Present a coherent defense of your research during the oral exam.',
    pronunciation: '/kəʊˈhɪə.rənt/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'university',
    synonyms: ['unified', 'systematic', 'orderly'],
    antonyms: ['disorderly', 'chaotic'],
  },
  {
    id: 'uni-15',
    word: 'peer-reviewed',
    translation_ru: 'рецензируемый',
    translation_kz: 'сарапталған',
    definition: 'evaluated by other people working in the same field before publication',
    example: 'Only cite peer-reviewed academic papers in scientific literature reviews.',
    pronunciation: '/ˌpɪə.rɪˈvjuːd/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'university',
    synonyms: ['scholarly', 'refereed', 'vetted'],
    antonyms: ['unverified'],
  },
  {
    id: 'uni-16',
    word: 'abstract',
    translation_ru: 'аннотация',
    translation_kz: 'аннотация',
    definition: 'a brief summary of a research article, thesis, review, or conference proceeding',
    example: 'Read the abstract first to see if the paper is relevant to your thesis.',
    pronunciation: '/ˈæb.strækt/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'university',
    synonyms: ['summary', 'synopsis', 'overview'],
    antonyms: [],
  },
  {
    id: 'uni-17',
    word: 'extrapolate',
    translation_ru: 'экстраполировать',
    translation_kz: 'болжамдау',
    definition: 'to estimate or conclude something by assuming that existing trends will continue',
    example: 'It is risky to extrapolate future consumer habits from a small sample size.',
    pronunciation: '/ɪkˈstræp.ə.leɪt/',
    part_of_speech: 'Verb',
    level: 'C1',
    category_id: 'university',
    synonyms: ['deduce', 'project', 'infer', 'predict'],
    antonyms: [],
  },
  {
    id: 'uni-18',
    word: 'fellowship',
    translation_ru: 'стипендия',
    translation_kz: 'стипендия',
    definition: 'a status granted to a university academic scholar along with financial stipend',
    example: 'She received a prestigious research fellowship at Cambridge University.',
    pronunciation: '/ˈfel.əʊ.ʃɪp/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'university',
    synonyms: ['grant', 'scholarship', 'endowment'],
    antonyms: [],
  },
  {
    id: 'uni-19',
    word: 'colloquium',
    translation_ru: 'коллоквиум',
    translation_kz: 'коллоквиум',
    definition: 'an academic conference or seminar where specialists discuss research topics',
    example: 'Graduate students presented their interim findings at the linguistics colloquium.',
    pronunciation: '/kəˈləʊ.kwi.əm/',
    part_of_speech: 'Noun',
    level: 'C1',
    category_id: 'university',
    synonyms: ['symposium', 'conference', 'seminar'],
    antonyms: [],
  },
  {
    id: 'uni-20',
    word: 'inquiry',
    translation_ru: 'исследование',
    translation_kz: 'зерттеу',
    definition: 'an act of asking for information or an official investigation and study',
    example: 'Scientific inquiry begins with asking insightful, testable questions.',
    pronunciation: '/ɪnˈkwaɪə.ri/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'university',
    synonyms: ['investigation', 'exploration', 'probe'],
    antonyms: [],
  },

  // --- WORK & BUSINESS (B1 - B2) ---
  {
    id: 'work-1',
    word: 'negotiate',
    translation_ru: 'вести переговоры',
    translation_kz: 'келіссөз жүргізу',
    definition: 'to obtain or bring about by discussion with opposing parties',
    example: 'The founder managed to negotiate favorable terms with angel investors.',
    pronunciation: '/nəˈɡəʊ.ʃi.eɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'work',
    synonyms: ['bargain', 'mediate', 'settle', 'transact'],
    antonyms: [],
  },
  {
    id: 'work-2',
    word: 'deadline',
    translation_ru: 'дедлайн',
    translation_kz: 'соңғы мерзім',
    definition: 'the latest time or date by which something should be completed',
    example: 'Our team worked diligently to deliver the milestone before the deadline.',
    pronunciation: '/ˈded.laɪn/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'work',
    synonyms: ['due date', 'target date', 'cutoff'],
    antonyms: [],
  },
  {
    id: 'work-3',
    word: 'collaborate',
    translation_ru: 'сотрудничать',
    translation_kz: 'ынтымақтасу',
    definition: 'to work jointly on an activity or project to produce something',
    example: 'Designers and developers collaborate closely in fast-paced product sprints.',
    pronunciation: '/kəˈlæb.ə.reɪt/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'work',
    synonyms: ['cooperate', 'team up', 'partner'],
    antonyms: ['compete', 'isolate'],
  },
  {
    id: 'work-4',
    word: 'productivity',
    translation_ru: 'продуктивность',
    translation_kz: 'өнімділік',
    definition: 'the state or quality of producing something efficiently and effectively',
    example: 'Eliminating distractions boosted overall team productivity by twenty percent.',
    pronunciation: '/ˌprɒd.ʌkˈtɪv.ə.ti/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'work',
    synonyms: ['efficiency', 'output', 'yield'],
    antonyms: ['unproductivity', 'idleness'],
  },
  {
    id: 'work-5',
    word: 'objective',
    translation_ru: 'цель',
    translation_kz: 'мақсат',
    definition: 'a specific result that a person or system aims to achieve within a timeframe',
    example: 'Our primary objective for Q3 is to increase monthly active learners.',
    pronunciation: '/əbˈdʒek.tɪv/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'work',
    synonyms: ['target', 'goal', 'aim', 'ambition'],
    antonyms: [],
  },
  {
    id: 'work-6',
    word: 'delegate',
    translation_ru: 'делегировать',
    translation_kz: 'тапсыру',
    definition: 'to entrust a task or responsibility to another person, typically a subordinate',
    example: 'An effective manager knows when to delegate routine administrative duties.',
    pronunciation: '/ˈdel.ɪ.ɡeɪt/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'work',
    synonyms: ['assign', 'entrust', 'hand over'],
    antonyms: ['hoard', 'retain'],
  },
  {
    id: 'work-7',
    word: 'revenue',
    translation_ru: 'доход компании',
    translation_kz: 'түсім',
    definition: 'the total amount of income generated by the sale of goods or services',
    example: 'Subscription models generate recurring revenue for SaaS startups.',
    pronunciation: '/ˈrev.ən.juː/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['income', 'turnover', 'earnings'],
    antonyms: ['expenditure', 'loss'],
  },
  {
    id: 'work-8',
    word: 'feedback',
    translation_ru: 'обратная связь',
    translation_kz: 'кері байланыс',
    definition: 'helpful information or critique given to someone to improve their performance',
    example: 'Constructive feedback from users shaped the latest mobile redesign.',
    pronunciation: '/ˈfiːd.bæk/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'work',
    synonyms: ['critique', 'input', 'evaluation', 'assessment'],
    antonyms: [],
  },
  {
    id: 'work-9',
    word: 'stakeholder',
    translation_ru: 'заинтересованная сторона',
    translation_kz: 'мүдделі тарап',
    definition: 'a person with an interest or concern in something, especially a business',
    example: 'We presented the product roadmap to all key stakeholders yesterday.',
    pronunciation: '/ˈsteɪkˌhəʊl.dər/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['investor', 'partner', 'shareholder'],
    antonyms: [],
  },
  {
    id: 'work-10',
    word: 'initiative',
    translation_ru: 'инициатива',
    translation_kz: 'бастама',
    definition: 'an act or strategy intended to resolve a problem or improve a situation',
    example: 'The company launched a green sustainability initiative across all offices.',
    pronunciation: '/ɪˈnɪʃ.ə.tɪv/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['enterprise', 'undertaking', 'venture'],
    antonyms: ['inertia'],
  },
  {
    id: 'work-11',
    word: 'benchmark',
    translation_ru: 'эталон',
    translation_kz: 'эталон',
    definition: 'a standard or point of reference against which things may be compared',
    example: 'Our app load speed is now the gold benchmark for language learning tools.',
    pronunciation: '/ˈbentʃ.mɑːk/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['standard', 'criterion', 'touchstone'],
    antonyms: [],
  },
  {
    id: 'work-12',
    word: 'competency',
    translation_ru: 'компетентность',
    translation_kz: 'құзыреттілік',
    definition: 'the ability to do something successfully or efficiently',
    example: 'The job posting lists English communication as a core core competency.',
    pronunciation: '/ˈkɒm.pɪ.tən.si/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['proficiency', 'expertise', 'capability'],
    antonyms: ['incompetence', 'inability'],
  },
  {
    id: 'work-13',
    word: 'compliance',
    translation_ru: 'соответствие нормам',
    translation_kz: 'талаптарға сәйкестік',
    definition: 'the action of obeying an order, regulation, or set of government standards',
    example: 'GDPR compliance guarantees the privacy rights of all application users.',
    pronunciation: '/kəmˈplaɪ.əns/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['adherence', 'conformity', 'observance'],
    antonyms: ['violation', 'defiance'],
  },
  {
    id: 'work-14',
    word: 'incentive',
    translation_ru: 'стимул',
    translation_kz: 'ынталандыру',
    definition: 'a thing that motivates or encourages someone to do something',
    example: 'Earning daily streak badges provides a compelling incentive to practice.',
    pronunciation: '/ɪnˈsen.tɪv/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['stimulus', 'motivation', 'inducement', 'carrot'],
    antonyms: ['deterrent', 'disincentive'],
  },
  {
    id: 'work-15',
    word: 'leverage',
    translation_ru: 'эффективно использовать',
    translation_kz: 'пайдалану',
    definition: 'to use something to maximum advantage to accomplish your objectives',
    example: 'Smart professionals leverage modern AI tools to accelerate work output.',
    pronunciation: '/ˈliː.vər.ɪdʒ/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'work',
    synonyms: ['utilize', 'exploit', 'harness'],
    antonyms: [],
  },
  {
    id: 'work-16',
    word: 'milestone',
    translation_ru: 'веха',
    translation_kz: 'белес',
    definition: 'a significant stage or event in the development of something',
    example: 'Reaching 500 active vocabulary words is a major learning milestone.',
    pronunciation: '/ˈmaɪl.stəʊn/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'work',
    synonyms: ['landmark', 'breakthrough', 'turning point'],
    antonyms: [],
  },
  {
    id: 'work-17',
    word: 'negotiation',
    translation_ru: 'переговоры',
    translation_kz: 'келіссөздер',
    definition: 'discussion aimed at reaching an agreement between different interests',
    example: 'The contract negotiation lasted three days before signing.',
    pronunciation: '/nəˌɡəʊ.ʃiˈeɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['dialogue', 'bargaining', 'arbitration'],
    antonyms: [],
  },
  {
    id: 'work-18',
    word: 'agenda',
    translation_ru: 'повестка дня',
    translation_kz: 'күн тәртібі',
    definition: 'a list of items to be discussed at a formal business meeting',
    example: 'Please review the team agenda before joining the sync call at 10 AM.',
    pronunciation: '/əˈdʒen.də/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'work',
    synonyms: ['schedule', 'itinerary', 'program'],
    antonyms: [],
  },
  {
    id: 'work-19',
    word: 'transparent',
    translation_ru: 'прозрачный',
    translation_kz: 'ашық',
    definition: 'open, clear, and easy to perceive or understand without deception',
    example: 'Modern leaders promote transparent communication throughout the company.',
    pronunciation: '/trænˈspær.ənt/',
    part_of_speech: 'Adjective',
    level: 'B2',
    category_id: 'work',
    synonyms: ['candid', 'honest', 'clear', 'straightforward'],
    antonyms: ['opaque', 'deceptive'],
  },
  {
    id: 'work-20',
    word: 'compensation',
    translation_ru: 'компенсация',
    translation_kz: 'өтемақы',
    definition: 'money awarded or salary paid to someone in exchange for work or loss',
    example: 'The job offer includes a generous compensation package and stock options.',
    pronunciation: '/ˌkɒm.penˈseɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'B2',
    category_id: 'work',
    synonyms: ['remuneration', 'salary', 'reimbursement'],
    antonyms: [],
  },

  // --- TRAVEL & MOBILITY (A1 - B1) ---
  {
    id: 'trv-1',
    word: 'destination',
    translation_ru: 'пункт назначения',
    translation_kz: 'межелі жер',
    definition: 'the place to which someone or something is going or being sent',
    example: 'Our flight destination is Tokyo, with a quick layover in Seoul.',
    pronunciation: '/ˌdes.tɪˈneɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['journey end', 'stop', 'target'],
    antonyms: ['origin', 'starting point'],
  },
  {
    id: 'trv-2',
    word: 'itinerary',
    translation_ru: 'маршрут поездки',
    translation_kz: 'саяхат бағыты',
    definition: 'a planned route or journey with scheduled stops and activities',
    example: 'She printed out the travel itinerary before heading to the departure gate.',
    pronunciation: '/aɪˈtɪn.ər.ər.i/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['route', 'travel plan', 'schedule'],
    antonyms: [],
  },
  {
    id: 'trv-3',
    word: 'accommodation',
    translation_ru: 'жилье',
    translation_kz: 'тұратын орын',
    definition: 'a room, group of rooms, or building in which someone may live or stay',
    example: 'We booked comfortable hotel accommodation near the historic town square.',
    pronunciation: '/əˌkɒm.əˈdeɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['lodging', 'housing', 'hotel', 'quarters'],
    antonyms: [],
  },
  {
    id: 'trv-4',
    word: 'departure',
    translation_ru: 'отправление',
    translation_kz: 'жөнелту',
    definition: 'the action of leaving, especially to start a journey',
    example: 'Passengers must arrive two hours prior to domestic flight departure.',
    pronunciation: '/dɪˈpɑː.tʃər/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['leaving', 'exit', 'takeoff'],
    antonyms: ['arrival'],
  },
  {
    id: 'trv-5',
    word: 'customs',
    translation_ru: 'таможня',
    translation_kz: 'кеден',
    definition: 'the official department that checks goods and luggage entering a country',
    example: 'After collecting your bags, proceed through international customs inspection.',
    pronunciation: '/ˈkʌs.təmz/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['border control', 'immigration'],
    antonyms: [],
  },
  {
    id: 'trv-6',
    word: 'reservation',
    translation_ru: 'бронирование',
    translation_kz: 'брондау',
    definition: 'an arrangement to secure a seat, room, or ticket at a later date',
    example: 'I have a dinner reservation for two under the name Damir.',
    pronunciation: '/ˌrez.əˈveɪ.ʃən/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['booking', 'order'],
    antonyms: ['cancellation'],
  },
  {
    id: 'trv-7',
    word: 'currency',
    translation_ru: 'валюта',
    translation_kz: 'валюта',
    definition: 'a system of money in general use in a particular country',
    example: 'It is advisable to exchange some cash currency before departing overseas.',
    pronunciation: '/ˈkʌr.ən.si/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['money', 'legal tender', 'coinage'],
    antonyms: [],
  },
  {
    id: 'trv-8',
    word: 'commute',
    translation_ru: 'ежедневная поездка',
    translation_kz: 'жол жүру',
    definition: 'to travel some distance between one home and place of work on a regular basis',
    example: 'His daily subway commute takes around thirty-five minutes each way.',
    pronunciation: '/kəˈmjuːt/',
    part_of_speech: 'Verb',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['travel', 'journey'],
    antonyms: [],
  },
  {
    id: 'trv-9',
    word: 'luggage',
    translation_ru: 'багаж',
    translation_kz: 'жүк',
    definition: 'suitcases or other bags in which to pack personal belongings for traveling',
    example: 'Keep fragile electronics in your carry-on luggage rather than checked bags.',
    pronunciation: '/ˈlʌɡ.ɪdʒ/',
    part_of_speech: 'Noun',
    level: 'A1',
    category_id: 'travel',
    synonyms: ['baggage', 'suitcases', 'bags'],
    antonyms: [],
  },
  {
    id: 'trv-10',
    word: 'boarding',
    translation_ru: 'посадка',
    translation_kz: 'отырғызу',
    definition: 'the act of getting on a plane, ship, train, or other vehicle',
    example: 'Flight 302 is now boarding passengers in rows twenty through thirty.',
    pronunciation: '/ˈbɔː.dɪŋ/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['embarkation', 'entraining'],
    antonyms: ['disembarkation'],
  },
  {
    id: 'trv-11',
    word: 'excursion',
    translation_ru: 'экскурсия',
    translation_kz: 'саяхат',
    definition: 'a short journey or trip, especially one engaged in as a leisure activity',
    example: 'We booked a guided walking excursion to see ancient mountain ruins.',
    pronunciation: '/ɪkˈskɜː.ʃən/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['tour', 'trip', 'outing', 'jaunt'],
    antonyms: [],
  },
  {
    id: 'trv-12',
    word: 'scenic',
    translation_ru: 'живописный',
    translation_kz: 'көрікті',
    definition: 'providing or relating to views of impressive natural scenery',
    example: 'We took the scenic coastal road to enjoy the breathtaking ocean sunset.',
    pronunciation: '/ˈsiː.nɪk/',
    part_of_speech: 'Adjective',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['picturesque', 'breathtaking', 'panoramic', 'charming'],
    antonyms: ['ugly', 'drab'],
  },
  {
    id: 'trv-13',
    word: 'delay',
    translation_ru: 'задержка',
    translation_kz: 'кешігу',
    definition: 'a period of time by which something is late or postponed',
    example: 'Due to severe fog, there was an unexpected two-hour flight delay.',
    pronunciation: '/dɪˈleɪ/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['postponement', 'lateness', 'setback'],
    antonyms: ['punctuality'],
  },
  {
    id: 'trv-14',
    word: 'souvenir',
    translation_ru: 'сувенир',
    translation_kz: 'кәдесый',
    definition: 'a thing that is kept as a reminder of a person, place, or event',
    example: 'She bought handmade ceramic mugs as a souvenir from Istanbul.',
    pronunciation: '/ˌsuː.vəˈnɪər/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['memento', 'keepsake', 'token'],
    antonyms: [],
  },
  {
    id: 'trv-15',
    word: 'foreign',
    translation_ru: 'иностранный',
    translation_kz: 'шетелдік',
    definition: 'of, from, in, or characteristic of a country or language other than one own',
    example: 'Speaking a foreign language opens doors to international friendships.',
    pronunciation: '/ˈfɒr.ɪn/',
    part_of_speech: 'Adjective',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['overseas', 'international', 'alien', 'exotic'],
    antonyms: ['domestic', 'native'],
  },
  {
    id: 'trv-16',
    word: 'explore',
    translation_ru: 'исследовать',
    translation_kz: 'зерттеу',
    definition: 'to travel through an unfamiliar area in order to learn about it',
    example: 'I love to explore narrow cobblestone streets in historic old towns.',
    pronunciation: '/ɪkˈsplɔːr/',
    part_of_speech: 'Verb',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['discover', 'scout', 'investigate'],
    antonyms: [],
  },
  {
    id: 'trv-17',
    word: 'sightseeing',
    translation_ru: 'осмотр достопримечательностей',
    translation_kz: 'көрікті жерлерді көру',
    definition: 'the activity of visiting places of interest in a particular location',
    example: 'We dedicated our Saturday afternoon to historic cathedral sightseeing.',
    pronunciation: '/ˈsaɪtˌsiː.ɪŋ/',
    part_of_speech: 'Noun',
    level: 'A2',
    category_id: 'travel',
    synonyms: ['touring', 'visiting'],
    antonyms: [],
  },
  {
    id: 'trv-18',
    word: 'embark',
    translation_ru: 'отправляться',
    translation_kz: 'аттану',
    definition: 'to go on board a ship, aircraft, or vehicle; to begin a new journey',
    example: 'They are about to embark on an exciting journey across South America.',
    pronunciation: '/ɪmˈbɑːk/',
    part_of_speech: 'Verb',
    level: 'B2',
    category_id: 'travel',
    synonyms: ['commence', 'board', 'start'],
    antonyms: ['disembark', 'end'],
  },
  {
    id: 'trv-19',
    word: 'remote',
    translation_ru: 'удаленный',
    translation_kz: 'қашық',
    definition: 'situated far from the main centers of population; distant and isolated',
    example: 'They spent the weekend cabin camping in a peaceful remote valley.',
    pronunciation: '/rɪˈməʊt/',
    part_of_speech: 'Adjective',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['isolated', 'distant', 'secluded'],
    antonyms: ['central', 'accessible'],
  },
  {
    id: 'trv-20',
    word: 'hospitality',
    translation_ru: 'гостеприимство',
    translation_kz: 'қонақжайлылық',
    definition: 'the friendly and generous reception and entertainment of guests or visitors',
    example: 'Kazakh culture is world-renowned for its warm and generous hospitality.',
    pronunciation: '/ˌhɒs.pɪˈtæl.ə.ti/',
    part_of_speech: 'Noun',
    level: 'B1',
    category_id: 'travel',
    synonyms: ['warmth', 'friendliness', 'welcome'],
    antonyms: ['hostility', 'coldness'],
  },

  // --- PHRASAL VERBS (A2 - B2) ---
  {
    id: 'pv-1',
    word: 'figure out',
    translation_ru: 'разобраться',
    translation_kz: 'түсіну',
    definition: 'to understand or solve something after thinking about it carefully',
    example: 'It took me twenty minutes to figure out the solution to the riddle.',
    pronunciation: '/ˈfɪɡ.ər aʊt/',
    part_of_speech: 'Phrasal Verb',
    level: 'B1',
    category_id: 'phrasal-verbs',
    synonyms: ['comprehend', 'solve', 'decipher'],
    antonyms: ['misunderstand'],
  },
  {
    id: 'pv-2',
    word: 'look forward to',
    translation_ru: 'ждать с нетерпением',
    translation_kz: 'асыға күту',
    definition: 'to feel happy and excited about something that is going to happen',
    example: 'I truly look forward to our next English conversation session.',
    pronunciation: '/lʊk ˈfɔː.wəd tuː/',
    part_of_speech: 'Phrasal Verb',
    level: 'A2',
    category_id: 'phrasal-verbs',
    synonyms: ['anticipate', 'await excitedly'],
    antonyms: ['dread'],
  },
  {
    id: 'pv-3',
    word: 'give up',
    translation_ru: 'сдаваться',
    translation_kz: 'берілу',
    definition: 'to stop making an effort; to cease an endeavor or habit',
    example: 'Never give up when learning complex grammatical patterns.',
    pronunciation: '/ɡɪv ʌp/',
    part_of_speech: 'Phrasal Verb',
    level: 'A2',
    category_id: 'phrasal-verbs',
    synonyms: ['surrender', 'quit', 'abandon'],
    antonyms: ['persevere', 'persist'],
  },
  {
    id: 'pv-4',
    word: 'come across',
    translation_ru: 'случайно натолкнуться',
    translation_kz: 'кездейсоқ кездестіру',
    definition: 'to find or meet someone or something by chance',
    example: 'I came across a fascinating idiom while reading the morning article.',
    pronunciation: '/kʌm əˈkrɒs/',
    part_of_speech: 'Phrasal Verb',
    level: 'B1',
    category_id: 'phrasal-verbs',
    synonyms: ['encounter', 'discover', 'bump into'],
    antonyms: [],
  },
  {
    id: 'pv-5',
    word: 'put off',
    translation_ru: 'откладывать на потом',
    translation_kz: 'кейінге қалдыру',
    definition: 'to postpone or delay something until a later time or date',
    example: 'Do not put off studying new vocabulary until the night before the exam.',
    pronunciation: '/pʊt ɒf/',
    part_of_speech: 'Phrasal Verb',
    level: 'B1',
    category_id: 'phrasal-verbs',
    synonyms: ['postpone', 'delay', 'defer'],
    antonyms: ['expedite', 'advance'],
  },
  {
    id: 'pv-6',
    word: 'carry on',
    translation_ru: 'продолжать',
    translation_kz: 'жалғастыру',
    definition: 'to continue an activity or task without stopping',
    example: 'Even if you make a mistake, take a breath and carry on speaking.',
    pronunciation: '/ˈkær.i ɒn/',
    part_of_speech: 'Phrasal Verb',
    level: 'A2',
    category_id: 'phrasal-verbs',
    synonyms: ['continue', 'proceed', 'persist'],
    antonyms: ['stop', 'halt'],
  },
  {
    id: 'pv-7',
    word: 'turn into',
    translation_ru: 'превращаться в',
    translation_kz: 'айналу',
    definition: 'to transform or be transformed into something else entirely',
    example: 'Small daily learning efforts turn into remarkable English fluency over time.',
    pronunciation: '/tɜːn ˈɪn.tuː/',
    part_of_speech: 'Phrasal Verb',
    level: 'B1',
    category_id: 'phrasal-verbs',
    synonyms: ['transform', 'become', 'convert into'],
    antonyms: [],
  },
  {
    id: 'pv-8',
    word: 'catch up with',
    translation_ru: 'догнать',
    translation_kz: 'қуып жету',
    definition: 'to reach the same level or standard as someone who was ahead',
    example: 'With persistent daily review, you will quickly catch up with your classmates.',
    pronunciation: '/kætʃ ʌp wɪð/',
    part_of_speech: 'Phrasal Verb',
    level: 'B1',
    category_id: 'phrasal-verbs',
    synonyms: ['overtake', 'reach', 'match'],
    antonyms: ['fall behind'],
  },
  {
    id: 'pv-9',
    word: 'bring about',
    translation_ru: 'вызывать, приводить к',
    translation_kz: 'алып келу',
    definition: 'to cause something to happen or bring about substantial change',
    example: 'Consistent active retrieval practice can bring about astonishing results.',
    pronunciation: '/brɪŋ əˈbaʊt/',
    part_of_speech: 'Phrasal Verb',
    level: 'B2',
    category_id: 'phrasal-verbs',
    synonyms: ['cause', 'engender', 'produce', 'induce'],
    antonyms: ['prevent'],
  },
  {
    id: 'pv-10',
    word: 'run out of',
    translation_ru: 'заканчиваться',
    translation_kz: 'таусылу',
    definition: 'to use up or finish the entire supply of something',
    example: 'Hurry up with the final questions before we run out of time!',
    pronunciation: '/rʌn aʊt əv/',
    part_of_speech: 'Phrasal Verb',
    level: 'A2',
    category_id: 'phrasal-verbs',
    synonyms: ['exhaust', 'deplete', 'consume'],
    antonyms: ['replenish'],
  },
];
